language: ruby
rvm:
  - 2.5.1
sudo: required
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_install:
  - gem update --system
  - gem install bundler
script:
  - export RAILS_ENV=test
  - bundle exec rails db:create db:migrate db:test:prepare
  - bundle exec rspec
bundler_args: --without production
